### ISSUE TITLE
cannot hide elevation of the appbar

### ISSUE THREAD

**Issue by itAlvy** [joostlek/GradientAppBar#13]
I need a consistent gradient color as a whole, but I can't hide the elevation of the appbar.
---

```dart
  @override
  Widget build(BuildContext context) {

    Widget regionalSelectionContainer = Container(
      decoration: BoxDecoration(
          gradient: LinearGradient(colors: [
            Color(0xff1AB99D),
            Color(0xff2E2888)
          ])
        )
      );
 
    return Scaffold(
      backgroundColor: Color(0xfff2f1f8),
      appBar: GradientAppBar( //  just copy, no modification
        gradientStart: Color(0xff1AB99D),
        gradientEnd: Color(0xff2E2888),
        elevation: 0, // -----------invalid------------
        title: Text('Regional Selection', style: TextStyle(fontSize: 14)),
        centerTitle: true,
      ),
      body: Container(child: regionalSelectionContainer,)
    );
  }
```
![Snipaste](https://user-images.githubusercontent.com/34973898/65298320-a2409280-db9d-11e9-84b7-4a7a5d615f3e.png)

**Comment by BondarenkoStas** [comment]
@itAlvy Please provide your ```flutter doctor -v``` and also specs what the emulator you use.

**Comment by joostlek** [comment]
First things first, I released an update, where you can instead of give a start and an end color, give a gradient. (so it would look like: 
```
@override
  Widget build(BuildContext context) {
    Gradient gradient =
        LinearGradient(colors: [Color(0xff1AB99D), Color(0xff2E2888)]);

    Widget regionalSelectionContainer =
        Container(decoration: BoxDecoration(gradient: gradient));

    return Scaffold(
        backgroundColor: Color(0xfff2f1f8),
        appBar: GradientAppBar(
          //  just copy, no modification
          gradient: gradient,
          elevation: 0, // -----------invalid------------
          title: Text('Regional Selection', style: TextStyle(fontSize: 14)),
          centerTitle: true,
        ),
        body: Container(
          child: regionalSelectionContainer,
        ));
  }
```

And when I run this, I get 
![image](https://user-images.githubusercontent.com/7083755/65386201-9d641600-dd38-11e9-806d-f3a775a964ac.png)

So could you maybe update your library and try it again?

**Comment by itAlvy** [comment]
> First things first, I released an update, where you can instead of give a start and an end color, give a gradient. (so it would look like:
> 
> ```
> @override
>   Widget build(BuildContext context) {
>     Gradient gradient =
>         LinearGradient(colors: [Color(0xff1AB99D), Color(0xff2E2888)]);
> 
>     Widget regionalSelectionContainer =
>         Container(decoration: BoxDecoration(gradient: gradient));
> 
>     return Scaffold(
>         backgroundColor: Color(0xfff2f1f8),
>         appBar: GradientAppBar(
>           //  just copy, no modification
>           gradient: gradient,
>           elevation: 0, // -----------invalid------------
>           title: Text('Regional Selection', style: TextStyle(fontSize: 14)),
>           centerTitle: true,
>         ),
>         body: Container(
>           child: regionalSelectionContainer,
>         ));
>   }
> ```
> 
> And when I run this, I get
> ![image](https://user-images.githubusercontent.com/7083755/65386201-9d641600-dd38-11e9-806d-f3a775a964ac.png)
> 
> So could you maybe update your library and try it again?

### Thank you, this is great. So should I update the flutter version? 
flutter version：**1.7.8**

![flutter version](https://user-images.githubusercontent.com/34973898/65398691-4c612a00-ddeb-11e9-9a45-02dcaa348ab0.png)

**Comment by joostlek** [comment]
You should change the version of gradient_app_bar to ^0.1.3, and then run flutter get again

**Comment by itAlvy** [comment]
> You should change the version of gradient_app_bar to ^0.1.3, and then run flutter get again

```dart
Gradient gradient =
        LinearGradient(colors: [Color(0xff1AB99D), Color(0xff2E2888)]);

    Widget regionalSelectionContainer =
        Container(decoration: BoxDecoration(gradient: gradient));

    return Scaffold(
        backgroundColor: Color(0xfff2f1f8),
        appBar: GradientAppBar(
          gradient: gradient,
          elevation: 0, // -----------invalid------------
          title: Text('Regional Selection', style: TextStyle(fontSize: 14)),
          centerTitle: true,
        ),
        body: Container(
          child: regionalSelectionContainer,
        ));
```
> gradient_app_bar: **^0.1.3** 
**import 'package:gradient_app_bar/gradient_app_bar.dart';**
## It seems that it still doesn't work, emmmm...

![微信截图_20190923142434](https://user-images.githubusercontent.com/34973898/65405282-2c8f2d80-de0e-11e9-8987-902a013e9055.png)

**Comment by joostlek** [comment]
Strange, do you still need me to look into it since you closed the issue?

**Comment by itAlvy** [comment]
> Strange, do you still need me to look into it since you closed the issue?



> Strange, do you still need me to look into it since you closed the issue?

Need help, I was accidentally shut down

**Comment by itAlvy** [comment]
> > Strange, do you still need me to look into it since you closed the issue?
> 
> Need help, I was accidentally shut down

**Comment by itAlvy** [comment]
> Strange, do you still need me to look into it since you closed the issue?

Need help, I was accidentally shut down
